language: node_js
node_js:
  - '9.0.0'
env:
  global:
  - secure: vAh29/+u3mYrugJCJ3EMWBD0W3vsI70/FUezg9X6LKcWapUw4DivVYE2KMrKqclzFdVljElB/H1rf4Cx2OpJX3uLC3lgP8avxEUyWm3HoFl4+SiibfQjQohgLOCuvf0LSUZnio0NSZ/YR1E3KnP/O7tamIzodfPDjrDSfdZS1ozN+Bex4zw2Q0zrftJiNUNcwuJzXbVJcUqnGa9KBCT0LJ7q0TE2DOlVMMca22Bo47x7ROqFCIVGEodJi0oIDYaxONigcikeemrQ16wUyh3HEGrwIwlasF8HGABkDQX+uYJGtpMtpmNFnjOwhKGtSmrnA77e9idkYgAXKyhrozCbItsSlJYECzdEFWrswzjfj3XN9kE0k5xroJv3iI9iVkBN1P9efMBe1UWdmw2Mz7PZzFEjhi0ZSwznPHix4S2Baf+vd2yPgqQwMlLDCyVLwuVZt7bqizBIqqWxylttCIp+CgKAAiq1gtlhZzGBvK0ZSYaN4eCN+DKAknlvoWoRXeLWg5TDMpts71Kngpgcim8uay/64tKqRIL4k20JjJGk6mNoYoC0tjarlYOhHactQ9w9JrmoAbFf1s1yzegvwU3w5ZPNG0rzGlmBBFQuq8WCke8OYO60GYgBcRiIzkXDRicfX3hA6vhX0qkchdNx6+MkWC213jF9UHQ48MYW3BlNwJk=
  - secure: QQ3a0IRiiMYhykYsW9pjP79Mp2BeJZRsTTrpwponw7P/jJgQ3sKh/5cvcyxFajSluU1BNEcd1L8+vqk9EKWZvJS90HDX4yTneNL4Sby3ACHECFHH8OUpT90LOX7ul1j8cK5t5dew6b/lVjsW5m1BJ74D5Zc8TKqwUIaVjzGqUeTgaQiSipqIZ6thQg5tRFp/IOYPKZxhWd8A7zuZQPTw6c+MJM/lmc77W5DXqq6FfdAO8gKtob4WIIsW8rXYqW21XBSwYzf80Oa+y8Wx/DG1CRccAUtnThj+3+bO/nuuDA4/Mld1V7WjxRBGthry8hNKCGVQOTEF5m29+8FVW2GYIxfZ0bRJa1hRKFSK4olb78uLZBidmKaGSRPL8QlnMRdHyHdx8W1TowQ1mHh2uM7TMAKkOawJWrYKTU3U25ZFRTjAbCURBZiql0GmTXLv1KHYqQXobmEnh/7GkZfCz0I7kwZps5mjX0LUB7BjE+0SVvGZ4YRrys4biLWCqFIPUuPh/xC1PboWgfETsNT/nvk2UA0nEuEo8Ocl3wLDEDQD4nhJe+pjUL71zl8IzWmiV9tgZGqSEOUwK8hj7OuHajneHu8UTTbHNGjoiKirU1/wpakiPSeijFSbE0ZtSbwSt5K4cXj8xN9ksrhALEVLOjHvbGvxN8Q7kpimlIz+humDtXg=
cache:
  directories:
    - "node_modules"
notifications:
  email:
    on_success: always
    on_failure: always
